health : Fixes missing @classmethod for __register__ function.
Error: unbound method __register__() must be called with
gnuhealth.pathology.group instance as first argument (got unicode instance
insted)